FROM python:3.7.11-slim-buster AS sqbase

ENV PATH=/root/.local/bin:$PATH
ENV PYTHONPATH=/root/.local/lib

RUN apt-get update && \
    pip install --upgrade pip

COPY build/requirements.txt /requirements.txt
RUN pip install --disable-pip-version-check -r /requirements.txt
