FROM python:3.7.11-slim-buster AS sqbase

ENV PATH=/root/.local/bin:$PATH
ENV PYTHONPATH=/root/.local/lib

COPY build/requirements.txt /requirements.txt

RUN apt-get update && \
    python -m pip install --upgrade pip && \
    python -m pip install --disable-pip-version-check -r /requirements.txt
