service: evpnVni
keys:
  - vni

show-fields:
  - vni
  - vlan
  - type
  - remoteVtepList
  - priVtepIp
  - secVtepIp

apply:
  cumulus:
    version: all
    command: sudo vtysh -c "show evpn vni detail json"
    normalize: '*/[
    "vni: vni",
    "type: type",
    "numMacs: numMacs?|0",
    "numArpNd: numArpNd?|0",
    "numRemoteVteps: remoteVtepList?|[]",
    "l2Vnis: l2VniList?|[]",
    "advertiseGatewayMacIp: advGateway?|False",
    "vtepIp: priVtepIp?|",
    "localVtepIp: priVtepIp?|priVtepIp",
    "vniFilter: vniFilter?|",
    "state: state?|up",
    "vxlanInterface: ifname?|",
    "routerMac: routerMac?|",
    "mcastGroup: mcastGroup?|",
    "vrf: vrf",
    "vxlanIntf: ifname?|ifname",
    ]'

  eos:
    version: all
    command: show interfaces Vxlan $
    normalize: 'interfaces/*/[
    "vlanToVniMap: _vlan2VniMap",
    "vlanToVtepList: _vlan2VtepMap?|{}",
    "srcIpAddr: priVtepIp",
    "name: ifname?|",
    "vrfToVniMap: _vrf2VniMap",
    "lineProtocolStatus: state",
    "replicationMode: replicationType",
    "floodMcastGrp: mcastGroup?|",
    ]'

  linux:
    copy: cumulus

  sonic:
    copy: cumulus

  junos-qfx:
    version: all
    command:
      - command: show evpn instance extensive | display json | no-more
        normalize: 'evpn-instance-information/[0]/evpn-instance/[
        "evpn-instance-name/[0]/data: vni?|0",
        "bridge-domain-status-table/[0]/bridge-domain/[*]/vlan-id/[0]/data: _vlanList?|[]",
        "bridge-domain-status-table/[0]/bridge-domain/[*]/domain-id/[0]/data: _vniList?|[]",
        "bridge-domain-status-table/[0]/bridge-domain/[*]/irb-interface/[0]/data: _irbList?|[]",
        "irb-interface-status-table/[0]/irb-interface/[*]/irb-interface-name/[0]/data: _irbIfList?|[]",
        "irb-interface-status-table/[0]/irb-interface/[*]/irb-interface-l3-context/[0]/data: _vrfList?|[]",
        "bridge-domain-status-table/[0]/bridge-domain/[*]/irb-interface/[0]/data: _irbList?|[]",
        "evpn-neighbor/[0]/evpn-neighbor-route-information/[*]/evpn-neighbor-address/[0]/data: remoteVtepList?|[]",
        "_entryType: _entryType?|instance",
        ]'

      - command: show evpn l3-context extensive | display json | no-more
        normalize: 'evpn-l3-context-information/[0]/evpn-l3-context/*/[
        "context-name/[0]/data: vrf",
        "context-vni/[0]/data: vni?|0",
        "context-source-vtep/[0]/vtep-address/[0]/data: priVtepIp?|",
        "context-router-mac/[0]/data: routerMac",
        "_entryType: _entryType?|l3",
        ]'
        
      - command: show ethernet-switching vxlan-tunnel-end-point remote | display json | no-more
        normalize: 'vxlan-source-vtep-information/[0]/svtep-format/*:source-vtep-address:priVtepIp|vxlan-remote-vtep-information/*/[
        "remote-vtep-address/[0]/data: _floodVtepList",
        "remote-vtep-mode: _mode",
        "remote-vtep-interface-name/[0]/data: vni?|0",
        "vxlan-dynamic-information/[0]/vxlan-format/[*]/vn-id/[0]/data: _vniList?|[]",
        "vxlan-dynamic-information/[0]/vxlan-format/[*]/multicast-address/[0]/data: replicationType",
        "_entryType: _entryType?|remote",
        ]'

  junos-ex:
    copy: junos-qfx

  junos-es:
    copy: junos-qfx

  junos-qfx10k:
    copy: junos-qfx

  nxos:
    - version: '> 9.3(0)'
      command:
       - command: show nve vni all detail | json native
         normalize: 'TABLE_nve_vni/ROW_nve_vni/*?/[
         "if-name: ifname",
         "vni: vni",
         "type: type",
         "vni-state: state",
         "vlan-bd: vlan?|0",
         "svi-state: _sviState",
         "mcast: replicationType",
         "_entryType: _entryType?|VNI",
         ]'

       - command: show nve interface nve 1 | json native
         normalize: 'TABLE_nve_if/ROW_nve_if/*?/[
         "primary-ip: priVtepIp",
         "encap-type: encapType",
         "source-if: vni",
         "if-name: ifname",
         "vpc-capability: _vpcCap?|",
         "secondary-ip: secVtepIp?|",
         "local-rmac: routerMac",
         "_entryType: _entryType?|iface",
         ]'

       - command: show nve peers detail | json native
         normalize: 'TABLE_nve_peers/ROW_nve_peers/*?/[
         "peer-ip: vni",
         "config-vnis: _configVnis",
         "cp-vni: _vniList?|",
         "_entryType: _entryType?|peers",
         ]'
