service: igmp
keys:
  - source
  - group
show-fields:
  - interfaceList
  - querier
  - flag

apply:
  eos:
    version: all
    command:
      - command: show ip igmp groups
        normalize: 'IgmpInterfaces/*:interface/[
        ]'
      - command: show ip igmp static-groups
        normalize: 'intfAddrs/*:interface/groupAddrsList/[
          "flag: flag?|Static",
        ]'
