service: igmp
keys:
  - interface
show-fields:
  - igmpVersion
  - joinedGroupList
  - querier
  - igmpEnabled
  - multicastRouting

  

apply:
  eos:
    version: all
    command: show ip igmp interface
    normalize: 'IgmpInterfaces/*:interface/[
      "igmpEnabled: igmpEnabled",
      "routerVersion: igmpVersion",
      "igmpQuerier: querier",
      "multicastRoutingEnabled: multicastRouting",
      "multicastGroups: joinedGroupList",
    ]'
