service: interfaces
keys:
  - ifname

show-fields:
  - ifname
  - state
  - adminState
  - type
  - mtu
  - master
  - ipAddressList
  - ip6AddressList

apply:
  cumulus:
    version: all
    command: sudo vtysh -c "show int vrf all"; ip -d address show
    textfsm: textfsm_templates/cl_interfaces.tfsm

  sonic:
    copy: cumulus

  eos:
    version: all
    command:
      - command: show interfaces
        # bunch of fields need code fixups. see service file
        normalize: 'interfaces/*/[
        "name: ifname",
        "mtu: mtu?|0",
        "description: description",
        "burnedInAddress: macaddr?|",
        "physicalAddress: macaddr?|macaddr",
        "bandwidth: speed?|0",
        "srcIpAddr: srcVtepIp",
        "vlanToVniMap/*: vlan?|0",
        "vlanToVniMap/*/vni: vni?|0",
        "lineProtocolStatus: state",
        "interfaceStatus: adminState",
        "hardware: type",
        "forwardingModel: forwardingModel",
        "linkStatusChanges: numChanges?|0",
        "lastStatusChangeTimeStamp": statusChangeTimestamp",
        "fallbackEnabled: lacpBypass?|False",
        "interfaceMembership: master?|",
        "interfaceAddress: ipAddressList?|[]",
        "interfaceAddressIP6: ip6AddressList?|[]",
        ]'

      - command: show vrf
        normalize: 'vrfs/*:ifname/[
        "vrfState: state",
        "type: type?|vrf",
        "routeDistinguisher: routeDistinguisher",
        "vni: vni?|0",
        "interfaces: _interfaceList?|[]"
        ]'

      - command: show ip virtual-router
        normalize: '/[
          "ifname: ifname?|varp",
          "type: type?|varp",
          "virtualMac: _anycastMac?|",
          "virtualMacs: _virtualMacs?|"
        ]'

  iosxe:
    version: all
    command:
      - command: show interfaces
        textfsm: textfsm_templates/iosxe_show_int.tfsm
      - command: show ip interface
        textfsm: textfsm_templates/iosxe_show_ip_int.tfsm
      - command: show ipv6 interface
        textfsm: textfsm_templates/iosxe_show_ipv6_int.tfsm
      - command: show vrf detail
        textfsm: textfsm_templates/iosxe_show_vrf.tfsm
        _entryType: vrf

  iosxr:
    version: all
    command:
      - command: show interfaces
        textfsm: textfsm_templates/iosxr_show_int.tfsm
      - command: show ipv4 interface 
        textfsm: textfsm_templates/iosxr_show_ip_int.tfsm
      - command: show ipv6 interface
        textfsm: textfsm_templates/iosxr_show_ipv6_int.tfsm
      - command: show vrf all detail
        textfsm: textfsm_templates/iosxr_show_vrf_detail.tfsm
        _entryType: vrf

  ios:
    copy: iosxe

  linux:
    version: all
    command: ip -d address show
    textfsm: textfsm_templates/linux_ipaddr.tfsm
  
  junos-qfx:
    version: all
    command:
      - command: show interface | display json | no-more
        normalize: 'interface-information/[0]/physical-interface/*/[
        "oper-status/[0]/data: state",
        "snmp-index/[0]/data: ifindex",
        "admin-status/[0]/data: adminState",
        "speed/[0]/data: speed?|0",
        "name/[0]/data: ifname",
        "description/[0]/data: description?|",
        "if-type/[0]/data: type?|",
        "link-level-type/[0]/data: type?|type",
        "mtu/[0]/data: mtu?|0",
        "minimum-links-in-aggregate/[0]/data: _minLinksBond",
        "current-physical-address/[0]/data: macaddr?|",
        "interface-flapped/[0]/attributes: statusChangeTimestamp?|",
        "logical-interface: _logIf",
        "logical-interface/[0]/encapsulation/[0]/data: master?|",
        "logical-interface/[*]/link-address/[0]/data: _vlanTag",
        ]'

      - command: show configuration routing-instances | display json | no-more
        normalize: 'configuration/routing-instances/instance/*/[
        "name: ifname",
        "instance-type: type?|vrf",
        "route-distinguisher/rd-type: routeDistinguisher",
        "interface/*/name: _interfaceList?|",
        "protocols/evpn/ip-prefix-routes/vni: vni?|0",
        ]'

  junos-ex:
    copy: junos-qfx

  junos-mx:
    copy: junos-qfx

  junos-es:
    copy: junos-qfx

  junos-qfx10k:
    copy: junos-qfx

  junos-evo:
    copy: junos-qfx

  nxos:
    - version: < 9.3(0)
      command:
        - command: show interface brief
          textfsm: textfsm_templates/nxos_show_int_brief.tfsm

        - command: show ip interface vrf all
          textfsm: textfsm_templates/nxos_show_ip_int.tfsm

        - command: show ipv6 interface vrf all
          textfsm: textfsm_templates/nxos_show_ipv6_int.tfsm

        - command: show interface | egrep '^\w|Hardware|MTU|reset|Description'
          textfsm: textfsm_templates/nxos_show_int_grep.tfsm
          _entryType: mtumac

        - command: show fabric forwarding internal svi-info
          textfsm: textfsm_templates/nxos_if_fabric.tfsm
          
        - command: show vrf detail
          textfsm: textfsm_templates/nxos_show_vrf.tfsm
          _entryType: vrf
            
    - version: all
      command:
        - command: show interface brief | json native
          normalize: 'TABLE_interface/ROW_interface/*?/[
           "interface: ifname",
           "state: state",
           "oper_state: state?|state",
           "svi_admin_state: state?|state",
           "speed: speed?|0",
           "mtu: mtu?|0",
           "portmode: _portmode?|routed",
           "portchan: _portchannel?|0",
           "type: type?|",
           "vlan: vlan?|0",
           "state_rsn_desc: reason",
           "svi_reason_desc: reason?|reason",
           ]'

        - command: show ip interface vrf all | json native
          normalize: 'TABLE_intf/ROW_intf/*?/[
          "vrf-name-out: vrf",
          "intf-name: ifname",
          "proto-state: state",
          "prefix: ipAddressList",
          "masklen: _maskLen",
          "admin-state: adminState",
          "mtu: mtu?|0",
          "unnum-intf: _unnum_intf?|",
          "TABLE_unnuminf/ROW_unnuminf/[*]?/unnum-child-inf: _child_intf?|[]",
          "TABLE_secondary_address/ROW_secondary_address/[*]?/prefix1: _secIPs?|[]",
          "TABLE_secondary_address/ROW_secondary_address/[*]?/masklen1: _secmasklens?|[]",
          ]'

        - command: show ipv6 interface vrf all | json native
          normalize: 'TABLE_intf/ROW_intf/*?/[
          "vrf-name-out: vrf",
          "intf-name: ifname",
          "admin-state: adminState",
          "TABLE_addr/ROW_addr/[*]?/addr: ip6AddressList?|[]",
          "linklocal-addr: _linklocal"
          ]'

        - command: show interface | egrep '^\w|Hardware|MTU|reset|Description|flapped'
          textfsm: textfsm_templates/nxos_show_int_grep.tfsm
          _entryType: mtumac

        - command: show fabric forwarding internal svi-info
          textfsm: textfsm_templates/nxos_if_fabric.tfsm

        - command: show vrf detail | json native
          normalize: 'TABLE_vrf/ROW_vrf/*/[
          "vrf_name: ifname?|",
          "vrf_state: state",
          "type: type?|vrf",
          "rd: routeDistinguisher",
          "mtu: mtu?|1500",
          "vni: vni?|0",
        ]'

  panos:
    version: all
    command: 
      - command: <show><system><state><filter>sw.dev.interface.config</filter></state></system></show>
        normalize: 'response/[result: _mtu_data]'
      
      - command: <show><interface>management</interface></show>
        normalize: 'response/result/info/[
          "name: ifname",
          "state: adminState",
          "ip: ipAddressList?|[]",
          "ipv6ll: ip6AddressList?|[]",
          "ipv6: _ip",
          "speed: speed?|-1",
          "hwaddr: macaddr",
        ]'

      - command: <show><interface>all</interface></show>
        normalize: 'response/result/hw/entry/*/[
          "name: ifname",
          "id: ifindex",
          "mac: macaddr",
          "speed: speed?|-1",
          "state: adminState",
          "st: state",
          "type: type",
        ]'

      - command: <show><interface>all</interface></show>
        normalize: 'response/result/ifnet/entry/*/[
          "name: ifname",
          "id: ifindex",
          "addr/member: ipAddressList?|[]",
          "addr6/member: ip6AddressList?|[]",
          "ip: _ip",
          "fwd: master"
        ]'
