service: mroutes
keys:
  - source
  - group
ignore-fields:
  - statusChangeTimestamp
show-fields:
  - source
  - group
  - rpfInterface
  - oifList
  - vrf
  - ipvers
  - rp
  - rpfNeighbor
  

apply:
  eos:
    version: all
    command: show ip mroute
    normalize: '*:protocol/groups/*:group/groupSources/*:source/[
    "rp: rp",
    "rpfInterface: rpfInterface",
    "rpf/rpfNeighbor: rpfNeighbor",
    "oifList: oifList",
    "vrf: vrf?|default"
    ]'
