service: mroutes
keys:
  - source
  - group
ignore-fields:
  - statusChangeTimestamp
show-fields:
  - source
  - group
  - rpfInterface
  - oifList
  - vrf
  - ipvers
  - rp
  - rpfNeighbor
  

apply:
  eos:
    version: all
    command: show ip mroute vrf Zone2
    normalize: '*:protocol/groups/*:group/groupSources/*:source/[
    "rp: rp",
    "rpfInterface: rpfInterface",
    "rpf/rpfNeighbor: rpfNeighbor",
    "oifList: oifList",
    "vrf: vrf?|default"
    ]'

  nxos:
    version: all
    command: show ip mroute vrf all | json
    normalize: 'TABLE_vrf/ROW_vrf/vrf-name:vrf|[
      "TABLE_one_route/ROW_one_route/[*]?/source_addrs: source",
      "TABLE_one_route/ROW_one_route/[*]?/group_addrs: group",
      "TABLE_one_route/ROW_one_route/[*]?/rpf-nbr": rpfNeighbor",
      "TABLE_one_route/ROW_one_route/[*]?/TABLE_oif/ROW_oif/[*]?/oif-name: oifList"
    ]'
