service: mroutes
keys:
  - vrf
  - sourceGroup
ignore-fields:
  - statusChangeTimestamp
show-fields:
  - sourceGroup
  - incomingInterface
  - oifList
  - vrf
  - ipvers
  

apply:
  eos:
    version: all
    command: show ip mroute vrf all
    normalize: 'vrfs/*:vrf/routes/*:prefix/[
        "routeType: protocol",
        "metric: metric?|0",
        "preference: preference?|0",
        "routeAction": "action?|forward",
        "hardwareProgrammed: hardwareProgrammed?|unknown",
        "vias/*/nexthopAddr: nexthopIps?|[]",
        "vias/*/interface: oifs?|[]",
        "vias/*/vtepAddr: _vtepAddr?|[]",
        "vias/*/vni: _vnis?|[]"
        ]'
