
service: ospfNbr
ignore-fields:
  - lastChangeTime
  - lastUpTime
  - lastDownTime
keys:
  - vrf
  - ifname
  - peerIP
show-fields:
  - vrf
  - ifname
  - state
  - peerIP
  - area
  - lastChangeTime
  - numChanges
apply:
  eos:
    version: all
    command: show ip ospf neighbor detail vrf all
    normalize: 'vrfs/*:vrf/instList/*:instance/ospfNeighborEntries/*/[
      "routerId: peerRouterId",
      "priority: nbrPrio",
      "interfaceName: ifname",
      "adjacencyState: state",
      "interfaceAddress: peerIP",
      "details/areaId: area",
      "details/stateTime: lastChangeTime",
      "details/bfdState: bfdStatus?|disabled",
      "details/numberOfStateChanges: numChanges",
      "options/externalRoutingCapability: areaStub?|False",
      "details/retransmissionCount: lsaRetxCnt"]'

  cumulus:
      version: all
      command:
        - command: sudo vtysh -c 'show ip ospf vrf all neighbor detail'
          textfsm: textfsm_templates/frr_ospfnbr.tfsm
        - command: sudo vtysh -c 'show ip ospf vrf all neighbor'
          textfsm: textfsm_templates/frr_ospfnbr_brief.tfsm

  linux:
    copy: cumulus

  sonic:
    copy: cumulus

  iosxe:
    version: all
    command: show ip ospf neighbor detail
    textfsm: textfsm_templates/iosxe_show_ip_ospfnbr.tfsm
      
  ios:
    copy: iosxe

  junos-qfx:
    version: all
    command:
      - command: show ospf neighbor instance all detail | display json | no-more
        normalize: 'ospf-neighbor-information-all/[0]/ospf-instance-neighbor/*:ospf-instance-name:vrf|ospf-neighbor/*/[
        "neighbor-address/[0]/data: peerIP",
        "interface-name/[0]/data: ifname",
        "ospf-neighbor-state/[0]/data: state",
        "neighbor-id/[0]/data: peerRouterId",
        "neighbor-priority/[0]/data: nbrPrio",
        "ospf-area/[0]/data: area",
        "neighbor-up-time/[0]/attributes: lastChangeTime?|"
        ]'

      - command: show bfd session detail | display json | no-more
        normalize: 'bfd-session-information/[0]/bfd-session/*/[
        "session-neighbor/[0]/data: _bfdIP?|",
        "session-state/[0]/data: bfdStatus?|",
        "session-interface/[0]/data: ifname",
        "bfd-client/[*]/client-name/[0]/data: _client?|",
        "_entryType: _entryType?|_bfdType",
        ]'

  junos-ex:
    copy: junos-qfx

  junos-mx:
    copy: junos-qfx

  junos-es:
    copy: junos-qfx

  junos-qfx10k:
    copy: junos-qfx

  nxos:
    - version: < 9.3(0)
      command: show ip ospf neighbor detail vrf all
      textfsm: textfsm_templates/nxos_show_ip_ospfnbr.tfsm
      
    - version: all
      command: show ip ospf neighbor detail vrf all | json native
      normalize: 'TABLE_ctx/ROW_ctx/*:cname:vrf|TABLE_nbr/ROW_nbr/*?/[
      "rid: peerRouterId",
      "addr: peerIP",
      "area: area",
      "intf: ifname",
      "state: state",
      "transition: numChanges?|0",
      "lastnonhello: lastChangeTime"
      ]'
