service: topmem
period: 60
type: counters
keys:
  - procName
  - pid
show-fields:
  - procName
  - pid
  - percentCPU
  - minLoadAvg
  - percentMem
  - residentMem
apply:
  cumulus:
    version: all
    command: top -bn 1 -o '%MEM' | head -17
    textfsm: textfsm_templates/cl_top.tfsm

  iosxr:
    version: all
    command: show processes memory
    textfsm: textfsm_templates/cl_top.tfsm

  linux:
    version: all
    command: top -bn 1 -o '%MEM' | head -17
    textfsm: textfsm_templates/linux_top.tfsm

  sonic:
    copy: linux

  eos:
    version: all
    command: bash timeout 4 top -bn 1 -N | head -17
    format: text
    textfsm: textfsm_templates/cl_top.tfsm
