
service: ospfNbr
ignore-fields:
  - lastChangeTime
  - lastUpTime
  - lastDownTime
keys:
  - vrf
  - ifname
show-fields:
  - vrf
  - ifname
  - state
  - peerIP
  - area
  - lastChangeTime
  - numChanges
apply:
  eos:
    version: all
    command: show ip ospf neighbor detail
    normalize: 'vrfs/*:vrf/instList/*:instance/ospfNeighborEntries/*/[
      "routerId: peerRouterId",
      "priority: nbrPrio",
      "interfaceName: ifname",
      "adjacencyState: state",
      "interfaceAddress: peerIP",
      "details/areaId: area",
      "details/stateTime: lastChangeTime",
      "details/bfdState: bfdStatus?|",
      "details/numberOfStateChanges: numChanges",
      "options/externalRoutingCapability: areaStub?|False",
      "details/retransmissionCount: lsaRetxCnt"]'

  cumulus:
      version: all
      command: sudo vtysh -c 'show ip ospf neighbor detail'
      textfsm: textfsm_templates/frr_ospfnbr.tfsm

  linux:
    copy: cumulus

  sonic:
    copy: cumulus

  junos-qfx:
    version: all
    command: show ospf neighbor instance all detail | display json | no-more
    normalize: 'ospf-neighbor-information-all/[0]/ospf-instance-neighbor/*:ospf-instance-name:vrf|ospf-neighbor/*/[
    "neighbor-address/[0]/data: peerIP",
    "interface-name/[0]/data: ifname",
    "ospf-neighbor-state/[0]/data: state",
    "neighbor-id/[0]/data: peerRouterId",
    "neighbor-priority/[0]/data: nbrPrio",
    "ospf-area/[0]/data: area",
    "neighbor-up-time/[0]/attributes: lastChangeTime?|"
    ]'

  junos-ex:
    copy: junos-qfx

  junos-mx:
    copy: junos-qfx

  nxos:
    version: all
    command: show ip ospf neighbor detail vrf all | json
    normalize: 'TABLE_ctx/ROW_ctx/*:cname:vrf|TABLE_nbr/ROW_nbr/*?/[
    "rid: peerRouterId",
    "addr: peerIP",
    "area: area",
    "intf: ifname",
    "state: state",
    "transition: numChanges?|0",
    "lastnonhello: lastChangeTime"
    ]'
